/**
 * Everyone named in the research document, and where the site discusses them.
 *
 * This is the answer to the question the site kept failing to answer: the
 * material carries more than a hundred people, and before this file they were
 * all buried inside paragraphs. Twenty of them have entries of their own, six
 * more are the core thinkers, and the rest are here with a line each and a link
 * to the page that deals with them.
 *
 * "name" is stored surname first so the index sorts the way an index should.
 * Nothing here is invented: if the document gives no dates, this file gives none.
 */

export interface RosterEntry {
  /** Surname first, as it should sort and display in the index. */
  name: string;
  /** One line on what they contribute. */
  note: string;
  /** Where to read about them on this site. */
  href: string;
  /** True when href is their own entry rather than a page that mentions them. */
  page?: boolean;
}

export const roster: RosterEntry[] = [
  { name: 'Adorno, Theodor W.', note: 'The culture industry, and the collaboration with Lazarsfeld that failed inside two years', href: '/milieus/radio-project' },
  { name: 'Agamben, Giorgio', note: 'The exception made permanent, and the COVID interventions that show a framework failing', href: '/thinkers/agamben', page: true },
  { name: 'Amadae, S. M.', note: 'How rational choice became the default language of political legitimacy', href: '/milieus/rand' },
  { name: 'Anderson, Perry', note: 'The sharpest internal critique of Gramsci, on three incompatible uses of civil society', href: '/thinkers/gramsci' },
  { name: 'Anyon, Jean', note: 'Fieldwork showing schools teach different relationships to authority by class', href: '/domains/education' },
  { name: 'Arendt, Hannah', note: 'Statelessness and the right to have rights', href: '/thinkers/agamben' },
  { name: 'Arrow, Kenneth', note: 'In the room at RAND as formal method acquired political authority', href: '/milieus/rand' },
  { name: 'Asch, Solomon', note: 'Conformity to visibly wrong group judgments, and it replicates', href: '/domains/psychology' },
  { name: 'Bateson, Gregory', note: 'Feedback applied to families and schooling, and the double bind', href: '/milieus/macy-conferences' },
  { name: 'Bell, Derrick', note: 'Critical Race Theory as the descendant of Critical Legal Studies', href: '/domains/law' },
  { name: 'Benjamin, Walter', note: 'Law-making violence as distinct from law-preserving violence', href: '/domains/law' },
  { name: 'Bernays, Edward', note: 'Invented public relations and published the method with pride', href: '/figures/bernays', page: true },
  { name: 'Bernstein, Basil', note: 'Elaborated and restricted linguistic codes, next to Bourdieu on cultural capital', href: '/thinkers/bourdieu' },
  { name: 'Bibó, István', note: 'The political culture and hysteria of small Eastern European states', href: '/east-west' },
  { name: 'Bourdieu, Pierre', note: 'The school converting inherited advantage into certified merit', href: '/thinkers/bourdieu', page: true },
  { name: 'Bowker, Geoffrey', note: 'Classification systems as political instruments nobody experiences as political', href: '/milieus/infrastructural-power' },
  { name: 'Bowles, Samuel', note: 'The correspondence principle: school reproduces the workforce structurally', href: '/domains/education' },
  { name: 'Brodie, Bernard', note: 'Nuclear strategy at RAND, where governance by model begins', href: '/milieus/rand' },
  { name: 'Brown, Wendy', note: 'Citizens converted into human capital, politics into competitiveness', href: '/milieus/control-after-discipline' },
  { name: 'Burgin, Angus', note: 'The making of the neoliberal movement, from the archives', href: '/milieus/mont-pelerin' },
  { name: 'Burnham, James', note: 'The managerial revolution, reaching Konrád and Szelényi’s conclusion from the West', href: '/milieus/elite-theory' },
  { name: 'Butler, Judith', note: 'Precarious life, as a counter-model to Agamben that keeps the concern', href: '/thinkers/agamben' },
  { name: 'Chakhotin, Serge', note: 'A Pavlov student analysing propaganda as conditioned reflex, and using it defensively', href: '/milieus/older-foundations' },
  { name: 'Chomsky, Noam', note: 'The propaganda model and its five filters, with the objections attached', href: '/domains/media' },
  { name: 'Cialdini, Robert', note: 'The persuasion practitioner’s field guide, best read defensively', href: '/domains/psychology' },
  { name: 'Coleman, Peter', note: 'The sympathetic insider account of the Congress for Cultural Freedom', href: '/milieus/congress-for-cultural-freedom' },
  { name: 'Cover, Robert', note: 'Legal interpretation always takes place on a field of pain and death', href: '/domains/law' },
  { name: 'Crenshaw, Kimberlé', note: 'Critical Race Theory, downstream of Critical Legal Studies', href: '/domains/law' },
  { name: 'Curtis, Adam', note: 'The best known visual entry point, and a case study in causation by juxtaposition', href: '/domains/media' },
  { name: 'Debord, Guy', note: 'The society of the spectacle, paired with Postman', href: '/domains/media' },
  { name: 'Deleuze, Gilles', note: 'Six pages on control as modulation, written before the web', href: '/figures/deleuze', page: true },
  { name: 'Elias, Norbert', note: 'External restraint becoming self-restraint across five centuries', href: '/milieus/institutions-and-persons' },
  { name: 'Ellsberg, Daniel', note: 'The best inside witness RAND has, because he defected', href: '/milieus/rand' },
  { name: 'Ellul, Jacques', note: 'Propaganda as a condition of mass society that works best on the educated', href: '/figures/ellul', page: true },
  { name: 'Erickson, Paul', note: 'Cold War rationality as a historical object rather than a timeless standard', href: '/milieus/rand' },
  { name: 'Eubanks, Virginia', note: 'Automated eligibility and risk scoring, tested on the poor first', href: '/milieus/behavioural-state' },
  { name: 'Ewen, Stuart', note: 'The historical record of advertising setting out to produce consumers as a type', href: '/domains/media' },
  { name: 'Festinger, Leon', note: 'Cognitive dissonance: having acted, we revise belief to match the act', href: '/domains/psychology' },
  { name: 'Fisher, Mark', note: 'Capitalist realism, on the inability to imagine an alternative', href: '/reading' },
  { name: 'Flusser, Vilém', note: 'The apparatus programmes the user who believes they are using it', href: '/milieus/media-materialism' },
  { name: 'Foucault, Michel', note: 'Discipline, biopolitics, governmentality, and power that produces rather than forbids', href: '/thinkers/foucault', page: true },
  { name: 'Frank, Jerome', note: 'American Legal Realism: judges decide, then justify', href: '/domains/law' },
  { name: 'Freire, Paulo', note: 'Banking education against critical consciousness, the constructive counterpart to Illich', href: '/counter-tradition' },
  { name: 'Gatto, John Taylor', note: 'The popular polemic on schooling. Provocation to verify, not a source to trust', href: '/domains/education' },
  { name: 'Gintis, Herbert', note: 'With Bowles, the correspondence principle and its later revision', href: '/domains/education' },
  { name: 'Goffman, Erving', note: 'The total institution, and the self an admission procedure takes apart', href: '/figures/goffman', page: true },
  { name: 'Graeber, David', note: 'The iron law of liberalism: deregulation reliably produces more bureaucracy', href: '/domains/bureaucracy' },
  { name: 'Gramsci, Antonio', note: 'Hegemony, common sense, and the war of position inside civil society', href: '/thinkers/gramsci', page: true },
  { name: 'Hall, Stuart', note: 'The most useful modern application of Gramsci', href: '/thinkers/gramsci' },
  { name: 'Han, Byung-Chul', note: 'The achievement society, where the subject exploits itself and calls it freedom', href: '/figures/han', page: true },
  { name: 'Havel, Václav', note: 'The greengrocer, living within a lie, and control that needs no belief', href: '/figures/havel', page: true },
  { name: 'Heims, Steve Joshua', note: 'The institutional history of the Macy Conferences', href: '/milieus/macy-conferences' },
  { name: 'Herman, Edward', note: 'With Chomsky, the propaganda model as a structural rather than conspiratorial claim', href: '/domains/media' },
  { name: 'Holmes, Oliver Wendell', note: 'Law as prophecies of what the courts will do in fact', href: '/domains/law' },
  { name: 'Holmes, Stephen', note: 'With Krastev, the politics of imitation after 1989', href: '/east-west' },
  { name: 'Horkheimer, Max', note: 'With Adorno, the culture industry as standardized industrial production', href: '/domains/media' },
  { name: 'Horwitz, Morton', note: 'Critical Legal Studies and the indeterminacy of doctrine', href: '/domains/law' },
  { name: 'Illich, Ivan', note: 'Radical monopoly, counterproductivity, and tools that disable their users', href: '/thinkers/illich', page: true },
  { name: 'Innis, Harold', note: 'Media biased toward time or space, and monopolies of knowledge', href: '/figures/innis', page: true },
  { name: 'Jackson, Philip', note: 'Coined the hidden curriculum: crowds, praise and power', href: '/domains/education' },
  { name: 'Jost, John', note: 'System justification, the experimental analogue of hegemony', href: '/domains/psychology' },
  { name: 'Jouvenel, Bertrand de', note: 'Centralization and emancipation advancing together, written under occupation', href: '/milieus/elite-theory' },
  { name: 'Judt, Tony', note: 'The reliable single-volume history underneath the East and West comparison', href: '/east-west' },
  { name: 'Kahn, Herman', note: 'On Thermonuclear War, and thinking the unthinkable in a model', href: '/milieus/rand' },
  { name: 'Kahneman, Daniel', note: 'Heuristics, biases and framing effects, with the replication caveat', href: '/domains/psychology' },
  { name: 'Kelsen, Hans', note: 'The pure theory of law, and the position Schmitt spent his career attacking', href: '/thinkers/schmitt' },
  { name: 'Kennedy, Duncan', note: 'Critical Legal Studies: competing principles justify opposite outcomes', href: '/domains/law' },
  { name: 'Kittler, Friedrich', note: 'Media as hardware with military ancestry. Media determine our situation', href: '/milieus/media-materialism' },
  { name: 'Kline, Ronald', note: 'The cybernetics moment, and what happened to it', href: '/milieus/macy-conferences' },
  { name: 'Konrád, György', note: 'With Szelényi, the intelligentsia becoming a ruling class under state socialism', href: '/east-west' },
  { name: 'Krastev, Ivan', note: 'The politics of imitation, and what being told to become a copy does to a society', href: '/east-west' },
  { name: 'La Boétie, Étienne de', note: 'Why do millions obey a man who has only the power they lend him', href: '/figures/la-boetie', page: true },
  { name: 'Lareau, Annette', note: 'Concerted cultivation against natural growth, the American empirical version', href: '/thinkers/bourdieu' },
  { name: 'Latour, Bruno', note: 'How facts and standards get built and then become invisible infrastructure', href: '/milieus/infrastructural-power' },
  { name: 'Lazarsfeld, Paul', note: 'Named the split himself: administrative research against critical research', href: '/milieus/radio-project' },
  { name: 'Le Bon, Gustave', note: 'Weak as science, historically decisive. Included for its effect, not its truth', href: '/milieus/older-foundations' },
  { name: 'Lerner, Melvin', note: 'The just-world hypothesis, producing victim-blaming and self-blame', href: '/domains/psychology' },
  { name: 'Lewin, Kurt', note: 'In the room at the Macy Conferences, carrying feedback into social psychology', href: '/milieus/macy-conferences' },
  { name: 'Lifton, Robert Jay', note: 'Eight criteria of thought reform, including loading the language', href: '/figures/lifton', page: true },
  { name: 'Lippmann, Walter', note: 'Coined the manufacture of consent, and meant it approvingly', href: '/figures/lippmann', page: true },
  { name: 'Llewellyn, Karl', note: 'American Legal Realism and the first break with law as logic', href: '/domains/law' },
  { name: 'MacLean, Nancy', note: 'Democracy in Chains, vigorously contested. Use it with the rebuttals', href: '/milieus/mont-pelerin' },
  { name: 'Mann, Horace', note: 'Visited Prussia in 1843 and imported mass schooling to Massachusetts', href: '/domains/education' },
  { name: 'Mann, Michael', note: 'Infrastructural power against despotic power, and why the first is the modern danger', href: '/milieus/infrastructural-power' },
  { name: 'Marcuse, Herbert', note: 'Repressive tolerance and false needs, with the paternalism objection', href: '/domains/psychology' },
  { name: 'Marks, John', note: 'Reconstructed the Cold War behavioural programmes from the files that survived', href: '/milieus/congress-for-cultural-freedom' },
  { name: 'Mbembe, Achille', note: 'Necropolitics: biopower seen from the colony rather than the metropole', href: '/figures/mbembe', page: true },
  { name: 'McCulloch, Warren', note: 'Chaired the Macy Conferences where cybernetics was assembled', href: '/milieus/macy-conferences' },
  { name: 'Mead, Margaret', note: 'Carried cybernetic vocabulary into anthropology from the Macy room', href: '/milieus/macy-conferences' },
  { name: 'Michels, Robert', note: 'The iron law of oligarchy, derived from the most democratic party of its day', href: '/figures/michels', page: true },
  { name: 'Milgram, Stanley', note: 'Obedience to authority, surviving in weakened form after the archival work', href: '/domains/psychology' },
  { name: 'Miller, Peter', note: 'With Rose, political power beyond the state, in twenty pages', href: '/figures/rose' },
  { name: 'Mills, C. Wright', note: 'Personal troubles into public issues, the founding move of this project', href: '/figures/mills', page: true },
  { name: 'Miłosz, Czesław', note: 'Ketman, and the self-division that consumes the self it protects', href: '/figures/milosz', page: true },
  { name: 'Mirowski, Philip', note: 'The neoliberal thought collective, from meeting minutes and funding structures', href: '/milieus/mont-pelerin' },
  { name: 'Mitchell, Timothy', note: 'Coal enabled the strike, oil engineered that leverage away', href: '/milieus/infrastructural-power' },
  { name: 'Morrison, David', note: 'The institutional history of the Princeton Radio Project', href: '/milieus/radio-project' },
  { name: 'Mosca, Gaetano', note: 'An organized minority always rules, and tells itself a political formula', href: '/figures/mosca', page: true },
  { name: 'Muller, Jerry', note: 'The tyranny of metrics, next to Goodhart and Campbell', href: '/domains/bureaucracy' },
  { name: 'Mumford, Lewis', note: 'The megamachine, and the monastery clock as the decisive machine', href: '/figures/mumford', page: true },
  { name: 'Müller, Jan-Werner', note: 'Schmitt’s postwar influence, running across the political spectrum', href: '/thinkers/schmitt' },
  { name: 'Noble, Safiya', note: 'Algorithms of oppression, in the contemporary behavioural cluster', href: '/milieus/behavioural-state' },
  { name: 'O’Neil, Cathy', note: 'Weapons of math destruction: scoring at scale, unaccountable', href: '/milieus/behavioural-state' },
  { name: 'Pareto, Vilfredo', note: 'Derivations and residues, and history as the circulation of elites', href: '/figures/pareto', page: true },
  { name: 'Pasquale, Frank', note: 'The black box society: authority that cannot be inspected', href: '/milieus/behavioural-state' },
  { name: 'Passeron, Jean-Claude', note: 'With Bourdieu, the study that set out educational reproduction', href: '/thinkers/bourdieu' },
  { name: 'Perry, Gina', note: 'The archival work that weakened the popular version of Milgram', href: '/domains/psychology' },
  { name: 'Pitts, Walter', note: 'With McCulloch, the neuron as a logical device, at the Macy Conferences', href: '/milieus/macy-conferences' },
  { name: 'Polanyi, Karl', note: 'The self-regulating market was itself an act of state construction', href: '/milieus/mont-pelerin' },
  { name: 'Postman, Neil', note: 'Huxley rather than Orwell: a medium that makes serious argument impossible', href: '/domains/media' },
  { name: 'Reimer, Everett', note: 'School Is Dead, alongside Illich on deschooling', href: '/thinkers/illich' },
  { name: 'Rose, Nikolas', note: 'How psychology made the self governable, and rule that works through freedom', href: '/figures/rose', page: true },
  { name: 'Schelling, Thomas', note: 'The strategy of conflict, and game theory as statecraft', href: '/milieus/rand' },
  { name: 'Schmitt, Carl', note: 'Sovereign is he who decides on the exception. Nazi party member from 1933', href: '/thinkers/schmitt', page: true },
  { name: 'Schumacher, E. F.', note: 'Small is beautiful, in the constructive line with Illich', href: '/thinkers/illich' },
  { name: 'Scott, James C.', note: 'Legibility, mētis, and the hidden transcript', href: '/figures/scott', page: true },
  { name: 'Scott-Smith, Giles', note: 'The politics of apolitical culture, on the cultural Cold War', href: '/milieus/congress-for-cultural-freedom' },
  { name: 'Seligman, Martin', note: 'Learned helplessness, the empirical form of disabling professions', href: '/domains/psychology' },
  { name: 'Shannon, Claude', note: 'Information theory, in the room where cybernetics was assembled', href: '/milieus/macy-conferences' },
  { name: 'Sharp, Gene', note: 'The strategic descendant of La Boétie on withdrawing consent', href: '/figures/la-boetie' },
  { name: 'Simpson, Christopher', note: 'How psychological-warfare funding shaped American communication research', href: '/milieus/radio-project' },
  { name: 'Skinner, B. F.', note: 'Argued openly for designing environments that produce behaviour', href: '/milieus/behavioural-state' },
  { name: 'Slobodian, Quinn', note: 'The Geneva School insulating markets from democratic majorities', href: '/milieus/mont-pelerin' },
  { name: 'Star, Susan Leigh', note: 'With Bowker, sorting things out: classification as silent politics', href: '/milieus/infrastructural-power' },
  { name: 'Stonor Saunders, Frances', note: 'The standard account of the CIA and the Congress for Cultural Freedom. Contested', href: '/milieus/congress-for-cultural-freedom' },
  { name: 'Sunstein, Cass', note: 'With Thaler, Nudge, read as a primary document of governing technique', href: '/domains/psychology' },
  { name: 'Szelényi, Iván', note: 'With Konrád, expert rule criticized from inside the East', href: '/east-west' },
  { name: 'Tarde, Gabriel', note: 'The public rather than the crowd, identified decades before broadcast', href: '/milieus/older-foundations' },
  { name: 'Thaler, Richard', note: 'Libertarian paternalism, which relies on the citizen not noticing', href: '/domains/psychology' },
  { name: 'Tilly, Charles', note: 'States as protection rackets that succeeded and then legitimated themselves', href: '/milieus/infrastructural-power' },
  { name: 'Tversky, Amos', note: 'With Kahneman, framing effects: the same information, different decisions', href: '/domains/psychology' },
  { name: 'Unger, Roberto', note: 'Critical Legal Studies, radicalizing the realist insight', href: '/domains/law' },
  { name: 'Veblen, Thorstein', note: 'Conspicuous consumption as status control, sabotage as normal business', href: '/milieus/older-foundations' },
  { name: 'Virilio, Paul', note: 'Dromology: political power as the control of speed and circulation', href: '/milieus/media-materialism' },
  { name: 'von Foerster, Heinz', note: 'Second-order cybernetics: the observer is inside the system observed', href: '/milieus/macy-conferences' },
  { name: 'von Neumann, John', note: 'At the Macy Conferences and at RAND, where the model became government', href: '/milieus/rand' },
  { name: 'Weber, Max', note: 'Rational-legal authority, the iron cage, and legitimacy as belief', href: '/domains/law' },
  { name: 'Wiener, Norbert', note: 'Built the science of control, then published his refusal of military funding', href: '/figures/wiener', page: true },
  { name: 'Willis, Paul', note: 'Working-class boys whose resistance to school delivers them into working-class jobs', href: '/thinkers/bourdieu' },
  { name: 'Winner, Langdon', note: 'Do artifacts have politics? Fifteen pages, argued through cases', href: '/milieus/media-materialism' },
  { name: 'Wittfogel, Karl', note: 'The hydraulic-state thesis, largely rejected. Read for how a discredited argument works', href: '/milieus/infrastructural-power' },
  { name: 'Wohlstetter, Albert', note: 'Deterrence analysis at RAND, and the authority of the formal model', href: '/milieus/rand' },
  { name: 'Young, Michael', note: 'Coined meritocracy in 1958 as a warning, and watched it adopted as a compliment', href: '/thinkers/bourdieu' },
  { name: 'Zimbardo, Philip', note: 'The Stanford Prison Experiment. A cautionary tale about evidence, not a finding', href: '/domains/psychology' },
  { name: 'Zinoviev, Alexander', note: 'Satirical anthropology of the character type the Soviet system produced', href: '/east-west' },
  { name: 'Zuboff, Shoshana', note: 'Behavioural surplus, prediction products, and the shift from predicting to shaping', href: '/figures/zuboff', page: true },
];
