/**
 * Every book, essay, lecture course and film named in the research document,
 * with the page on this site that discusses it.
 *
 * Years are given only where the document gives them. Where it does not, the
 * field is left out rather than filled in from memory.
 */

export interface Work {
  author: string;
  title: string;
  year?: string;
  /** What it is, in a few words, where that is not obvious from the title. */
  note?: string;
  /** The page on this site that discusses it. */
  href: string;
  /** Marked contested or discredited on the site, and why in one phrase. */
  contested?: string;
}

export const works: Work[] = [
  { author: 'Adorno, Theodor W.', title: 'Scientific Experiences of a European Scholar in America', year: '1969', note: 'His own account of the collision with audience research', href: '/milieus/radio-project' },
  { author: 'Adorno and Horkheimer', title: 'Dialectic of Enlightenment', year: '1944', note: 'The culture industry', href: '/domains/media' },
  { author: 'Agamben, Giorgio', title: 'Homo Sacer', year: '1995', href: '/thinkers/agamben' },
  { author: 'Agamben, Giorgio', title: 'State of Exception', year: '2003', href: '/thinkers/agamben' },
  { author: 'Agamben, Giorgio', title: 'Remnants of Auschwitz', year: '1998', href: '/thinkers/agamben' },
  { author: 'Agamben, Giorgio', title: 'What Is an Apparatus?', year: '2006', href: '/thinkers/agamben' },
  { author: 'Amadae, S. M.', title: 'Rationalizing Capitalist Democracy', year: '2003', href: '/milieus/rand' },
  { author: 'Anderson, Perry', title: 'The Antinomies of Antonio Gramsci', href: '/thinkers/gramsci' },
  { author: 'Anyon, Jean', title: 'Social Class and the Hidden Curriculum of Work', year: '1980', href: '/domains/education' },
  { author: 'Arendt, Hannah', title: 'The Origins of Totalitarianism', href: '/thinkers/agamben' },
  { author: 'Bateson, Gregory', title: 'Steps to an Ecology of Mind', year: '1972', href: '/milieus/macy-conferences' },
  { author: 'Benjamin, Walter', title: 'Critique of Violence', year: '1921', href: '/domains/law' },
  { author: 'Bernays, Edward', title: 'Crystallizing Public Opinion', year: '1923', href: '/figures/bernays' },
  { author: 'Bernays, Edward', title: 'Propaganda', year: '1928', href: '/figures/bernays' },
  { author: 'Bourdieu, Pierre', title: 'The Inheritors', year: '1964', href: '/thinkers/bourdieu' },
  { author: 'Bourdieu, Pierre', title: 'Distinction', year: '1979', href: '/thinkers/bourdieu' },
  { author: 'Bourdieu, Pierre', title: 'The Forms of Capital', year: '1986', note: 'The best short entry point', href: '/thinkers/bourdieu' },
  { author: 'Bourdieu, Pierre', title: 'Language and Symbolic Power', year: '1991', href: '/thinkers/bourdieu' },
  { author: 'Bourdieu and Passeron', title: 'Reproduction in Education, Society and Culture', year: '1970', href: '/thinkers/bourdieu' },
  { author: 'Bowker and Star', title: 'Sorting Things Out', year: '1999', href: '/milieus/infrastructural-power' },
  { author: 'Bowles and Gintis', title: 'Schooling in Capitalist America', year: '1976', note: 'The correspondence principle', href: '/domains/education' },
  { author: 'Brown, Wendy', title: 'Undoing the Demos', year: '2015', href: '/milieus/control-after-discipline' },
  { author: 'Burgin, Angus', title: 'The Great Persuasion', year: '2012', href: '/milieus/mont-pelerin' },
  { author: 'Burnham, James', title: 'The Managerial Revolution', year: '1941', href: '/milieus/elite-theory' },
  { author: 'Burnham, James', title: 'The Machiavellians', year: '1943', href: '/milieus/elite-theory' },
  { author: 'Butler, Judith', title: 'Precarious Life', href: '/thinkers/agamben' },
  { author: 'Chakhotin, Serge', title: 'The Rape of the Masses', year: '1939', href: '/milieus/older-foundations' },
  { author: 'Cialdini, Robert', title: 'Influence', year: '1984', href: '/domains/psychology' },
  { author: 'Coleman, Peter', title: 'The Liberal Conspiracy', year: '1989', href: '/milieus/congress-for-cultural-freedom' },
  { author: 'Cover, Robert', title: 'Violence and the Word', href: '/domains/law' },
  { author: 'Curtis, Adam', title: 'The Century of the Self', note: 'Documentary, on Bernays', href: '/domains/media', contested: 'Criticized for implying causation through juxtaposition' },
  { author: 'Curtis, Adam', title: 'HyperNormalisation', note: 'Documentary', href: '/domains/media', contested: 'Same caveat as above' },
  { author: 'Curtis, Adam', title: "Can't Get You Out of My Head", note: 'Documentary', href: '/domains/media', contested: 'Same caveat as above' },
  { author: 'Debord, Guy', title: 'The Society of the Spectacle', year: '1967', href: '/domains/media' },
  { author: 'Deleuze, Gilles', title: 'Postscript on the Societies of Control', year: '1990', note: 'Six pages, the highest-yield short text here', href: '/figures/deleuze' },
  { author: 'Elias, Norbert', title: 'The Civilizing Process', year: '1939', href: '/milieus/institutions-and-persons' },
  { author: 'Ellsberg, Daniel', title: 'Secrets', year: '2002', href: '/milieus/rand' },
  { author: 'Ellsberg, Daniel', title: 'The Doomsday Machine', year: '2017', href: '/milieus/rand' },
  { author: 'Ellul, Jacques', title: 'Propaganda: The Formation of Men’s Attitudes', year: '1962', href: '/figures/ellul' },
  { author: 'Erickson, Paul, and others', title: 'How Reason Almost Lost Its Mind', year: '2013', href: '/milieus/rand' },
  { author: 'Eubanks, Virginia', title: 'Automating Inequality', year: '2018', href: '/milieus/behavioural-state' },
  { author: 'Ewen, Stuart', title: 'Captains of Consciousness', year: '1976', href: '/domains/media' },
  { author: 'Ewen, Stuart', title: 'PR! A Social History of Spin', year: '1996', href: '/domains/media' },
  { author: 'Fisher, Mark', title: 'Capitalist Realism', href: '/reading' },
  { author: 'Flusser, Vilém', title: 'Towards a Philosophy of Photography', year: '1983', href: '/milieus/media-materialism' },
  { author: 'Foucault, Michel', title: 'Madness and Civilization', year: '1961', href: '/thinkers/foucault' },
  { author: 'Foucault, Michel', title: 'The Birth of the Clinic', year: '1963', href: '/thinkers/foucault' },
  { author: 'Foucault, Michel', title: 'Discipline and Punish', year: '1975', note: 'Start here. Part three is Panopticism', href: '/thinkers/foucault' },
  { author: 'Foucault, Michel', title: 'The History of Sexuality, Volume 1', year: '1976', href: '/thinkers/foucault' },
  { author: 'Foucault, Michel', title: 'Security, Territory, Population', year: '1978', note: 'Lecture course', href: '/thinkers/foucault' },
  { author: 'Foucault, Michel', title: 'The Birth of Biopolitics', year: '1979', note: 'Lecture course, where governmentality is worked out', href: '/thinkers/foucault' },
  { author: 'Freire, Paulo', title: 'Pedagogy of the Oppressed', year: '1968', href: '/counter-tradition' },
  { author: 'Gatto, John Taylor', title: 'The Underground History of American Education', href: '/domains/education', contested: 'Loose sourcing. Provocation to verify, not a source' },
  { author: 'Gatto, John Taylor', title: 'Dumbing Us Down', href: '/domains/education', contested: 'Same caveat as above' },
  { author: 'Goffman, Erving', title: 'The Presentation of Self in Everyday Life', year: '1956', href: '/figures/goffman' },
  { author: 'Goffman, Erving', title: 'Asylums', year: '1961', note: 'The total institution', href: '/figures/goffman' },
  { author: 'Goffman, Erving', title: 'Stigma', year: '1963', href: '/figures/goffman' },
  { author: 'Graeber, David', title: 'Debt: The First 5,000 Years', year: '2011', href: '/domains/bureaucracy' },
  { author: 'Graeber, David', title: 'The Utopia of Rules', year: '2015', note: 'The iron law of liberalism', href: '/domains/bureaucracy' },
  { author: 'Graeber, David', title: 'Bullshit Jobs', year: '2018', href: '/domains/bureaucracy' },
  { author: 'Gramsci, Antonio', title: 'Selections from the Prison Notebooks', year: '1971', note: 'Hoare and Nowell-Smith, the standard English gateway', href: '/thinkers/gramsci' },
  { author: 'Han, Byung-Chul', title: 'The Burnout Society', year: '2010', href: '/figures/han' },
  { author: 'Han, Byung-Chul', title: 'Psychopolitics', year: '2014', href: '/figures/han' },
  { author: 'Havel, Václav', title: 'The Power of the Powerless', year: '1978', note: 'The greengrocer. Read this one first', href: '/figures/havel' },
  { author: 'Heims, Steve Joshua', title: 'The Cybernetics Group', year: '1991', href: '/milieus/macy-conferences' },
  { author: 'Herman and Chomsky', title: 'Manufacturing Consent', year: '1988', note: 'The propaganda model and its five filters', href: '/domains/media' },
  { author: 'Illich, Ivan', title: 'Deschooling Society', year: '1971', href: '/thinkers/illich' },
  { author: 'Illich, Ivan', title: 'Tools for Conviviality', year: '1973', note: 'The design brief for anything built from this material', href: '/thinkers/illich' },
  { author: 'Illich, Ivan', title: 'Energy and Equity', year: '1974', href: '/thinkers/illich' },
  { author: 'Illich, Ivan', title: 'Medical Nemesis, published in Britain as Limits to Medicine', year: '1975', href: '/thinkers/illich' },
  { author: 'Illich, Ivan', title: 'Disabling Professions', year: '1977', href: '/thinkers/illich' },
  { author: 'Innis, Harold', title: 'Empire and Communications', year: '1950', href: '/figures/innis' },
  { author: 'Innis, Harold', title: 'The Bias of Communication', year: '1951', href: '/figures/innis' },
  { author: 'Jackson, Philip', title: 'Life in Classrooms', year: '1968', note: 'Coined the hidden curriculum', href: '/domains/education' },
  { author: 'Jouvenel, Bertrand de', title: 'On Power', year: '1945', href: '/milieus/elite-theory' },
  { author: 'Judt, Tony', title: 'Postwar', year: '2005', href: '/east-west' },
  { author: 'Kahn, Herman', title: 'On Thermonuclear War', year: '1960', href: '/milieus/rand' },
  { author: 'Katz and Lazarsfeld', title: 'Personal Influence', year: '1955', note: 'The two-step flow', href: '/milieus/radio-project' },
  { author: 'Kelsen, Hans', title: 'Pure Theory of Law', note: 'The position Schmitt attacks. Read both', href: '/thinkers/schmitt' },
  { author: 'Kittler, Friedrich', title: 'Discourse Networks 1800/1900', href: '/milieus/media-materialism' },
  { author: 'Kittler, Friedrich', title: 'Gramophone, Film, Typewriter', year: '1986', href: '/milieus/media-materialism' },
  { author: 'Kline, Ronald', title: 'The Cybernetics Moment', year: '2015', href: '/milieus/macy-conferences' },
  { author: 'Konrád and Szelényi', title: 'The Intellectuals on the Road to Class Power', year: '1979', href: '/east-west' },
  { author: 'Krastev and Holmes', title: 'The Light That Failed', year: '2019', href: '/east-west' },
  { author: 'La Boétie, Étienne de', title: 'Discourse on Voluntary Servitude', year: 'c. 1548', href: '/figures/la-boetie' },
  { author: 'Lareau, Annette', title: 'Unequal Childhoods', year: '2003', href: '/thinkers/bourdieu' },
  { author: 'Lazarsfeld, Paul', title: 'Remarks on Administrative and Critical Communications Research', year: '1941', note: 'Short, and the key document in this cluster', href: '/milieus/radio-project' },
  { author: 'Lazarsfeld, Berelson and Gaudet', title: 'The People’s Choice', year: '1944', href: '/milieus/radio-project' },
  { author: 'Le Bon, Gustave', title: 'The Crowd', year: '1895', href: '/milieus/older-foundations', contested: 'Weak as science, included for its historical effect' },
  { author: 'Lifton, Robert Jay', title: 'Thought Reform and the Psychology of Totalism', year: '1961', href: '/domains/psychology' },
  { author: 'Lippmann, Walter', title: 'Public Opinion', year: '1922', note: 'Coined the manufacture of consent', href: '/figures/lippmann' },
  { author: 'MacLean, Nancy', title: 'Democracy in Chains', year: '2017', href: '/milieus/mont-pelerin', contested: 'Vigorously contested. Use with the rebuttals' },
  { author: 'Mann, Michael', title: 'The Sources of Social Power', year: '1986 to 2012', note: 'Four volumes', href: '/milieus/infrastructural-power' },
  { author: 'Marcuse, Herbert', title: 'One-Dimensional Man', year: '1964', href: '/domains/psychology' },
  { author: 'Marks, John', title: 'The Search for the Manchurian Candidate', year: '1979', href: '/milieus/congress-for-cultural-freedom' },
  { author: 'Mbembe, Achille', title: 'Necropolitics', year: '2003', href: '/figures/mbembe' },
  { author: 'Michels, Robert', title: 'Political Parties', year: '1911', note: 'The iron law of oligarchy', href: '/figures/michels' },
  { author: 'Mills, C. Wright', title: 'The Power Elite', year: '1956', href: '/figures/mills' },
  { author: 'Mills, C. Wright', title: 'The Sociological Imagination', year: '1959', note: 'Chapter one is where this project starts', href: '/figures/mills' },
  { author: 'Miłosz, Czesław', title: 'The Captive Mind', year: '1953', note: 'Ketman', href: '/figures/milosz' },
  { author: 'Mirowski, Philip', title: 'Never Let a Serious Crisis Go to Waste', year: '2013', href: '/milieus/mont-pelerin' },
  { author: 'Mirowski and Plehwe', title: 'The Road from Mont Pèlerin', year: '2009', note: 'The archival collection', href: '/milieus/mont-pelerin' },
  { author: 'Mitchell, Timothy', title: 'Rule of Experts', year: '2002', href: '/milieus/infrastructural-power' },
  { author: 'Mitchell, Timothy', title: 'Carbon Democracy', year: '2011', href: '/milieus/infrastructural-power' },
  { author: 'Mosca, Gaetano', title: 'The Ruling Class', year: '1896', href: '/figures/mosca' },
  { author: 'Muller, Jerry', title: 'The Tyranny of Metrics', year: '2018', href: '/domains/bureaucracy' },
  { author: 'Mumford, Lewis', title: 'Technics and Civilization', year: '1934', href: '/figures/mumford' },
  { author: 'Mumford, Lewis', title: 'The Myth of the Machine', year: '1967 and 1970', note: 'The megamachine', href: '/figures/mumford' },
  { author: 'Müller, Jan-Werner', title: 'A Dangerous Mind', href: '/thinkers/schmitt' },
  { author: 'Noble, Safiya', title: 'Algorithms of Oppression', year: '2018', href: '/milieus/behavioural-state' },
  { author: 'O’Neil, Cathy', title: 'Weapons of Math Destruction', year: '2016', href: '/milieus/behavioural-state' },
  { author: 'Pareto, Vilfredo', title: 'The Mind and Society', year: '1916', href: '/figures/pareto' },
  { author: 'Pasquale, Frank', title: 'The Black Box Society', year: '2015', href: '/milieus/behavioural-state' },
  { author: 'Perry, Gina', title: 'Behind the Shock Machine', note: 'The archival work on Milgram', href: '/domains/psychology' },
  { author: 'Polanyi, Karl', title: 'The Great Transformation', year: '1944', href: '/milieus/mont-pelerin' },
  { author: 'Postman, Neil', title: 'Amusing Ourselves to Death', year: '1985', href: '/domains/media' },
  { author: 'Reimer, Everett', title: 'School Is Dead', href: '/thinkers/illich' },
  { author: 'Rose, Nikolas', title: 'Governing the Soul', year: '1989', href: '/figures/rose' },
  { author: 'Rose, Nikolas', title: 'Powers of Freedom', year: '1999', href: '/figures/rose' },
  { author: 'Rose and Miller', title: 'Political Power beyond the State', year: '1992', note: 'The compact statement', href: '/figures/rose' },
  { author: 'Schelling, Thomas', title: 'The Strategy of Conflict', year: '1960', href: '/milieus/rand' },
  { author: 'Schmitt, Carl', title: 'Political Theology', year: '1922', href: '/thinkers/schmitt' },
  { author: 'Schmitt, Carl', title: 'The Crisis of Parliamentary Democracy', year: '1923', href: '/thinkers/schmitt' },
  { author: 'Schmitt, Carl', title: 'The Concept of the Political', year: '1932', note: 'Friend and enemy', href: '/thinkers/schmitt' },
  { author: 'Schumacher, E. F.', title: 'Small Is Beautiful', href: '/thinkers/illich' },
  { author: 'Scott, James C.', title: 'Domination and the Arts of Resistance', year: '1990', note: 'The hidden transcript', href: '/figures/scott' },
  { author: 'Scott, James C.', title: 'Seeing Like a State', year: '1998', note: 'Legibility and mētis', href: '/figures/scott' },
  { author: 'Simpson, Christopher', title: 'Science of Coercion', year: '1994', note: 'Underread, and the key text on the funding of communication research', href: '/milieus/radio-project' },
  { author: 'Skinner, B. F.', title: 'Walden Two', year: '1948', href: '/milieus/behavioural-state' },
  { author: 'Skinner, B. F.', title: 'Beyond Freedom and Dignity', year: '1971', href: '/milieus/behavioural-state' },
  { author: 'Slobodian, Quinn', title: 'Globalists', year: '2018', href: '/milieus/mont-pelerin' },
  { author: 'Stonor Saunders, Frances', title: 'The Cultural Cold War, published in Britain as Who Paid the Piper?', year: '1999', href: '/milieus/congress-for-cultural-freedom', contested: 'The standard account, disputed by participants' },
  { author: 'Tarde, Gabriel', title: 'L’opinion et la foule', year: '1901', href: '/milieus/older-foundations' },
  { author: 'Thaler and Sunstein', title: 'Nudge', year: '2008', note: 'Read as a primary document of governing technique', href: '/domains/psychology' },
  { author: 'Tilly, Charles', title: 'War Making and State Making as Organized Crime', year: '1985', href: '/milieus/infrastructural-power' },
  { author: 'Tilly, Charles', title: 'Coercion, Capital, and European States', year: '1990', href: '/milieus/infrastructural-power' },
  { author: 'Veblen, Thorstein', title: 'The Theory of the Leisure Class', year: '1899', href: '/milieus/older-foundations' },
  { author: 'Veblen, Thorstein', title: 'The Engineers and the Price System', year: '1921', href: '/milieus/older-foundations' },
  { author: 'Virilio, Paul', title: 'Speed and Politics', year: '1977', href: '/milieus/media-materialism' },
  { author: 'Wiener, Norbert', title: 'A Scientist Rebels', year: '1947', note: 'The published refusal of military funding', href: '/figures/wiener' },
  { author: 'Wiener, Norbert', title: 'Cybernetics', year: '1948', href: '/figures/wiener' },
  { author: 'Wiener, Norbert', title: 'The Human Use of Human Beings', year: '1950, revised 1954', note: 'Read both editions against each other', href: '/figures/wiener' },
  { author: 'Willis, Paul', title: 'Learning to Labour', year: '1977', href: '/thinkers/bourdieu' },
  { author: 'Winner, Langdon', title: 'Do Artifacts Have Politics?', year: '1980', href: '/milieus/media-materialism' },
  { author: 'Wittfogel, Karl', title: 'Oriental Despotism', year: '1957', href: '/milieus/infrastructural-power', contested: 'The hydraulic-state thesis, largely rejected' },
  { author: 'Young, Michael', title: 'The Rise of the Meritocracy', year: '1958', note: 'A satire, adopted as a compliment', href: '/thinkers/bourdieu' },
  { author: 'Zinoviev, Alexander', title: 'Homo Sovieticus', year: '1982', href: '/east-west' },
  { author: 'Zuboff, Shoshana', title: 'The Age of Surveillance Capitalism', year: '2019', href: '/figures/zuboff' },
  { author: 'Various', title: 'The Corporation', year: '2003', note: 'Documentary', href: '/reading' },
  { author: 'Various', title: 'The Lives of Others', year: '2006', note: 'Film, the Eastern surveillance state', href: '/reading' },
  { author: 'Various', title: 'Videocracy', year: '2009', note: 'Documentary, on Berlusconi’s media hegemony', href: '/reading' },
];
